# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9667e45afc1a31453cc91d9f4f9419e9fa727e9f301afb81ef80b0e770825e9f53f6d506baa6573cc6ffb3707d310918123a68e4916f7a5bac3cae8489e90ed

test:
  secret_key_base: a2951efdb741b90558801aeef6fb604e755cbf7ac11a1be3bf5e048747fa1e5f110b618d716fcf21e9406591e8053a03911835e5ac25d362696d8afd8279fcb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
